import Navbar from '@/app/_components/navbar'
import { geistMono, geistSans } from '@/lib/fonts'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next Auth Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-stone-100 font-[family-name:var(--font-geist-sans)] antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
